### ISSUE TITLE
I cannot import hpelm anymore

### ISSUE THREAD

**Issue by juanantoniobellido** [akusok/hpelm#19]
I cannot import hpelm. Anytime I try, the following error appears:
_

> Traceback (most recent call last):
>   File "c:/Users/jabel/OneDrive - Universidad de Córdoba/Scripts_python/et0-reg-private/get_reg_et0_by_elm.py", line 13, in <module>
>     import lib.ml_models.elm_regression as ELM
>   File "c:\Users\jabel\OneDrive - Universidad de Córdoba\Scripts_python\et0-reg-private\lib\ml_models\elm_regression.py", line 12, in <module>
>     import hpelm
>   File "C:\Users\jabel\.conda\envs\agroml\lib\site-packages\hpelm\__init__.py", line 7, in <module>
>     from .elm import ELM
>   File "C:\Users\jabel\.conda\envs\agroml\lib\site-packages\hpelm\elm.py", line 11, in <module>
>     from tables import open_file
>   File "C:\Users\jabel\.conda\envs\agroml\lib\site-packages\tables\__init__.py", line 45, in <module>
>     from .utilsextension import get_hdf5_version as _get_hdf5_version
> ImportError: DLL load failed while importing utilsextension: No se puede encontrar el módulo especificado.

_

My conda environment is the following:
_

> # Name                    Version                   Build  Channel
> absl-py                   0.15.0                   pypi_0    pypi
> asttokens                 2.0.5                    pypi_0    pypi
> astunparse                1.6.3                    pypi_0    pypi
> atomicwrites              1.4.0                    pypi_0    pypi
> attrs                     21.4.0                   pypi_0    pypi
> backcall                  0.2.0                    pypi_0    pypi
> ca-certificates           2021.10.26           haa95532_4
> cachetools                5.0.0                    pypi_0    pypi
> certifi                   2021.10.8        py38haa95532_2
> charset-normalizer        2.0.12                   pypi_0    pypi
> colorama                  0.4.4                    pypi_0    pypi
> cycler                    0.11.0                   pypi_0    pypi
> debugpy                   1.5.1                    pypi_0    pypi
> decorator                 5.1.1                    pypi_0    pypi
> entrypoints               0.4                      pypi_0    pypi
> ephem                     4.1.3                    pypi_0    pypi
> et-xmlfile                1.1.0                    pypi_0    pypi
> executing                 0.8.2                    pypi_0    pypi
> fasteners                 0.17.3                   pypi_0    pypi
> flatbuffers               1.12                     pypi_0    pypi
> fonttools                 4.29.1                   pypi_0    pypi
> gast                      0.4.0                    pypi_0    pypi
> google-auth               2.6.0                    pypi_0    pypi
> google-auth-oauthlib      0.4.6                    pypi_0    pypi
> google-pasta              0.2.0                    pypi_0    pypi
> grpcio                    1.34.1                   pypi_0    pypi
> h5py                      3.1.0                    pypi_0    pypi
> hpelm                     1.0.10                   pypi_0    pypi
> icecream                  2.1.2                    pypi_0    pypi
> idna                      3.3                      pypi_0    pypi
> importlib-metadata        4.11.1                   pypi_0    pypi
> iniconfig                 1.1.1                    pypi_0    pypi
> ipykernel                 6.9.1                    pypi_0    pypi
> ipython                   8.1.1                    pypi_0    pypi
> jedi                      0.18.1                   pypi_0    pypi
> joblib                    1.1.0                    pypi_0    pypi
> jupyter-client            7.1.2                    pypi_0    pypi
> jupyter-core              4.9.2                    pypi_0    pypi
> keras-nightly             2.5.0.dev2021032900          pypi_0    pypi
> keras-preprocessing       1.1.2                    pypi_0    pypi
> kiwisolver                1.3.2                    pypi_0    pypi
> markdown                  3.3.6                    pypi_0    pypi
> matplotlib                3.5.1                    pypi_0    pypi
> matplotlib-inline         0.1.3                    pypi_0    pypi
> nest-asyncio              1.5.4                    pypi_0    pypi
> nose                      1.3.7                    pypi_0    pypi
> numexpr                   2.8.1                    pypi_0    pypi
> numpy                     1.19.5                   pypi_0    pypi
> oauthlib                  3.2.0                    pypi_0    pypi
> openpyxl                  3.0.9                    pypi_0    pypi
> openssl                   1.1.1m               h2bbff1b_0
> opt-einsum                3.3.0                    pypi_0    pypi
> packaging                 21.3                     pypi_0    pypi
> pandas                    1.4.1                    pypi_0    pypi
> parso                     0.8.3                    pypi_0    pypi
> pickleshare               0.7.5                    pypi_0    pypi
> pillow                    9.0.1                    pypi_0    pypi
> pip                       21.2.2           py38haa95532_0
> pluggy                    1.0.0                    pypi_0    pypi
> prompt-toolkit            3.0.28                   pypi_0    pypi
> protobuf                  3.19.4                   pypi_0    pypi
> pure-eval                 0.2.2                    pypi_0    pypi
> py                        1.11.0                   pypi_0    pypi
> pyaml                     21.10.1                  pypi_0    pypi
> pyasn1                    0.4.8                    pypi_0    pypi
> pyasn1-modules            0.2.8                    pypi_0    pypi
> pygments                  2.11.2                   pypi_0    pypi
> pyparsing                 3.0.7                    pypi_0    pypi
> pytest                    7.0.1                    pypi_0    pypi
> python                    3.8.12               h6244533_0
> python-dateutil           2.8.2                    pypi_0    pypi
> pytz                      2021.3                   pypi_0    pypi
> pywin32                   303                      pypi_0    pypi
> pyyaml                    6.0                      pypi_0    pypi
> pyzmq                     22.3.0                   pypi_0    pypi
> requests                  2.27.1                   pypi_0    pypi
> requests-oauthlib         1.3.1                    pypi_0    pypi
> rsa                       4.8                      pypi_0    pypi
> scikit-learn              1.0.2                    pypi_0    pypi
> scikit-optimize           0.9.0                    pypi_0    pypi
> scipy                     1.8.0                    pypi_0    pypi
> setuptools                58.0.4           py38haa95532_0
> six                       1.15.0                   pypi_0    pypi
> sqlite                    3.37.2               h2bbff1b_0
> stack-data                0.2.0                    pypi_0    pypi
> tables                    3.7.0                    pypi_0    pypi
> tensorboard               2.8.0                    pypi_0    pypi
> tensorboard-data-server   0.6.1                    pypi_0    pypi
> tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
> tensorflow                2.5.0                    pypi_0    pypi
> tensorflow-estimator      2.5.0                    pypi_0    pypi
> termcolor                 1.1.0                    pypi_0    pypi
> threadpoolctl             3.1.0                    pypi_0    pypi
> tomli                     2.0.1                    pypi_0    pypi
> tornado                   6.1                      pypi_0    pypi
> tqdm                      4.62.3                   pypi_0    pypi
> traitlets                 5.1.1                    pypi_0    pypi
> typing-extensions         3.7.4.3                  pypi_0    pypi
> urllib3                   1.26.8                   pypi_0    pypi
> vc                        14.2                 h21ff451_1
> vs2015_runtime            14.27.29016          h5e58377_2
> wcwidth                   0.2.5                    pypi_0    pypi
> werkzeug                  2.0.3                    pypi_0    pypi
> wheel                     0.37.1             pyhd3eb1b0_0
> wincertstore              0.2              py38haa95532_2
> wrapt                     1.12.1                   pypi_0    pypi
> xlwt                      1.3.0                    pypi_0    pypi
> zipp                      3.7.0                    pypi_0    pypi

_

I have try to run it on VSCode and Pycharm. I also uninstall and reinstall (even a different version).

Any clue about what is happening and how to resolve it? Because in other computers it is actually working.

**Comment by juanantoniobellido** [comment]
I created a new environment, reinstalled everything and it is working now.

**Comment by Xuzhou2245** [comment]
Which version of python are you using? Can you share the requirements.txt file?
