### ISSUE TITLE
multilayer elm

### ISSUE THREAD

**Issue by btekgit** [akusok/hpelm#2]
Hi, this may not be best place to ask but I am trying to train a multilayer ELM. Unfortunately, it produces results very similar to a single layer classification ELM, which is poorer than a simple random forest classifier. I copied how I configure it below. Do I miss anything? Thanks.
 input shape is 
(18356L, 7500L) max:  1.0 min:  -1.0
ninputsig = 40
ninputlin = 3

    ## INPUT LAYER - DOES AUTO ENCODER
    elmInput = ELM(input_shape, input_shape)
    elmInput.add_neurons(ninputsig, "sigm")
    elmInput.add_neurons(ninputlin, "lin")
    elmInput.train(XXtrainIn, XXtrainOut,"r") 
    print "\n Trained input elm",elmInput
    elmInputProjection= elmInput.project(XXtrainIn)    

    ## HIDDEN LAYER    
    elmHidden1 = ELM(elmInputProjection.shape[1], elmInputProjection.shape[1])
    elmHidden1.add_neurons(ninputsig, "sigm")
    elmHidden1.add_neurons(ninputlin, "lin")
    elmHidden1.train(elmInputProjection, XXtrainOut,"r")
    elmHiddenProjection= elmHidden1.project(elmInputProjection)
    
    # OUTPUT LAYER 
    elmOutput = ELM(elmHiddenProjection.shape[1], YY.shape[1])
    elmOutput.add_neurons(ninputsig, "sigm")
    elmOutput.add_neurons(ninputlin, "lin")
    
    # now I should bring all samples here. 
    inputproj = elmInput.project(XXtrainIn)
    hiddenproj = elmHidden1.project(inputproj)
    elmOutput.train(hiddenproj, YYtrain,"wc", w=[0.5, 0.5])
    
    
    # now prediction for trainining
    prjinput = elmInput.project(XXtrainIn)
    prjhidden = elmHidden1.project(prjinput)
    youtput = elmOutput.predict(prjhidden)
    
    
    # training results
    mse_error = elmOutput.error(youtput, YYtrain)
    print "Training mse:", mse_error
    p = ytrain.squeeze()
    yout = np.argmax(youtput, axis = 1)
    nhit = sum(yout==p)
    ntpos = sum((yout==1) & (p==1))
    npos = sum((p==1))
    print "\n Training results"
    print "Tpos:",ntpos," / ", npos, "TD:", ntpos/float(npos)
    print "Acc: ", nhit/(float)(len(p)), "total", len(p)

**Comment by akusok** [comment]
Hello,

I tried multi-layer ELM only a couple of times, and got a bit worse results than for a single-layer ELM, like you did.
But I am not an expert in multi-layer ELMs. You should ask people who published those papers, maybe there are special parameters which I don't know.

I would suggest to try model structure selection (use "CV" or "LOO" flags in "train()" method), that normally improves results of ELM. Even better results can be obtained with "OP" flag that chooses the best performing neurons, but it can run longer. See more here: http://hpelm.readthedocs.org/en/latest/api/elm.html#hpelm.elm.ELM.train <http://hpelm.readthedocs.org/en/latest/api/elm.html#hpelm.elm.ELM.train>

Best regards,
Anton Akusok

**Comment by btekgit** [comment]
Thanks.
