### ISSUE TITLE
Dimensionality of input/output data parameters annoying

### ISSUE THREAD

**Issue by mertyildiran** [akusok/hpelm#3]
Could we remove dimensionality of input/output data constraints because it's really bothering me when I'm trying to train same network with arbitrary length of data.

I'm talking about the simple functionality like in this project: https://github.com/lepisma/ELM.jl

I'm suffering this problem in here: https://github.com/mertyildiran/Cerebrum/blob/f81351a8c27a4cf6fc76bf79fa35e2c8ed49ef75/cerebrum/neuralnet/weaver.py

I don't want to limit the length of input. In ELM.jl project output is also arbitrary and depends on the length of the input. I can crop the output or fill with zeros but I don't want to limit the input length.

Do you have any idea? Thanks a lot for this great library.

**Comment by mertyildiran** [comment]
I think I was wrong about ELM.jl library. But anyway, how can I get around from this dimensionality problem?

**Comment by mertyildiran** [comment]
It was a stupid question, I'm so sorry. I'm closing this issue.

**Comment by akusok** [comment]
Hello Mehmet,

The input dimensionality is used for automatic generation of neurons before ELM sees any data. If you still want it removed - I can do that, but then generation of neurons has to be delayed until an ELM gets training data, and that complicates the code somewhat.

Anyway, hope that you like the toolbox. Good luck with your project!

Best regards,
Anton Akusok
